language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache: pip

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install ant
  - pip install tox-travis
  - bash ./scripts/get_cpachecker.sh
  - pip install .

script:
  - tox
  - bash ./scripts/benchmark.sh

after_success:
  pip install codecov && codecov


jobs:
  include:
    - stage: "Deploy - Docker Hub"
      language: generic
      if: branch = master AND type != pull_request
      services:
        - docker
      script:
        # test docker build
        - travis_wait 30 docker build . -t cmlapsu/shadowdp
        - docker run -it cmlapsu/shadowdp bash /shadowdp/scripts/benchmark.sh
        - docker run -it cmlapsu/shadowdp bash /shadowdp/scripts/verify.sh
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        - docker push cmlapsu/shadowdp:latest

    - stage: "Deploy - Github"
      language: generic
      if: branch = master AND type != pull_request
      # cannot use deploy: pages since it does not support custom commit message yet
      script:
        - rm -rf .git
        - git init
        - git config user.name "Yuxin (Ryan) Wang"
        - git config user.email "ryanwang.cs@gmail.com"
        - git add .
        - git commit -m "Release of ShadowDP."
        - git remote add origin https://ryanwanggit:$GITHUB_TOKEN@github.com/cmla-psu/shadowdp.git
        - git push -u --force origin master

notifications:
  email: false
