language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache: pip

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install ant
  - pip install tox-travis
  - bash ./scripts/get_cpachecker.sh
  - python setup.py install

script:
  - java -version
  - javac -version
  - tox
  - bash ./scripts/benchmark.sh

after_success:
  pip install codecov && codecov


jobs:
  include:
    - stage: deploy
      services:
        - docker
      script:
        # test docker build
        - docker build . -t cmlapsu/shadowdp
        - docker run -it cmlapsu/shadowdp bash /shadowdp/scripts/benchmark.sh

      after_success:
        # only deploy on stable master branch
        - if [[ "$TRAVIS_BRANCH" = "master" && $TRAVIS_PULL_REQUEST = "false" ]]; then
            echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin;
            docker push cmlapsu/shadowdp:latest;
            rm -rf .git;
            git init;
            git config user.name "Yuxin (Ryan) Wang";
            git config user.email "ryanwang.cs@gmail.com";
            git add .;
            git commit -m "Release of ShadowDP.";
            git remote add origin https://ryanwanggit:$GITHUB_TOKEN@github.com/cmla-psu/shadowdp.git;
            git push -u --force origin master;
          fi

notifications:
  email: false
